# Config file for travis-ci.org

language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.cache/phpcs

before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh

before_script:
  - which phpcs || { wget -c https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -O ~/.local/bin/phpcs && chmod a+rx ~/.local/bin/phpcs; }
  - test -d ~/.local/share/phpcs/PHPCompatibility || git clone -b 7.0.6 https://github.com/wimg/PHPCompatibility.git ~/.local/share/phpcs/PHPCompatibility
  - phpcs --config-set installed_paths ~/.local/share/phpcs

script:
  - phpunit -c _test --stderr --group plugin_pageredirect
  - phpcs -v --standard=PHPCompatibility --runtime-set testVersion 5.3-7.0 --ignore=_test/ lib/plugins/pageredirect

# vim:ts=2:sw=2:et
